// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDos_XUZlI7vwpGVCPhAirMXPaeAlQD8AM',
    appId: '1:708390293197:web:7a1de4f44df1546576a384',
    messagingSenderId: '708390293197',
    projectId: 'flutterblog-c24df',
    authDomain: 'flutterblog-c24df.firebaseapp.com',
    storageBucket: 'flutterblog-c24df.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEwM2z8mOxnkR_5I4iwwOg9uyPEuiKBoo',
    appId: '1:708390293197:android:d66e0a2e8216ed1376a384',
    messagingSenderId: '708390293197',
    projectId: 'flutterblog-c24df',
    storageBucket: 'flutterblog-c24df.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBP4DQSFvCnRAAEV1YmqkWnGpHisx8iSP4',
    appId: '1:708390293197:ios:a73e5e08f3ce8bee76a384',
    messagingSenderId: '708390293197',
    projectId: 'flutterblog-c24df',
    storageBucket: 'flutterblog-c24df.appspot.com',
    iosBundleId: 'com.example.flutterBlog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBP4DQSFvCnRAAEV1YmqkWnGpHisx8iSP4',
    appId: '1:708390293197:ios:7c420060d99a88b476a384',
    messagingSenderId: '708390293197',
    projectId: 'flutterblog-c24df',
    storageBucket: 'flutterblog-c24df.appspot.com',
    iosBundleId: 'com.example.flutterBlog.RunnerTests',
  );
}
